### ISSUE TITLE
Website: Änderung der Farben

### ISSUE THREAD

**Issue by Fourigin-GbR** [Fourigin-GbR/4igin-website#1]
Farben

rot: #e30613
weiss: #e7e7e7
dunkel_grau: #3d3d3d
hell_grau: #8e8e8e

Schriften 

Gill Sans Regular
Chalkduster

**Comment by kschaefer76** [comment]
Ich hab keine Ahnung. Vlad?

**Comment by Michael-Krug** [comment]
Done.
